#!groovy
pipeline {
    agent any
    triggers {
        pollSCM 'H/2 * * * *'
    }
    stages {
        stage('Github') {
            steps {
                git branch: 'main', url: 'https://github.com/txtbits/subscription.git'
            }
        }
        stage('Build') {
            steps {
                sh './mailservice/gradlew -p ./mailservice assemble'
            }
        }
        stage('Test') {
            steps {
                sh './mailservice/gradlew -p ./mailservice test'
            }
        }
        stage('Build Docker image') {
            steps {
                sh './mailservice/gradlew -p ./mailservice docker'
            }
        }
        stage('Push Docker image') {
            environment {
                DOCKER_HUB_LOGIN = credentials('docker-hub')
            }
            steps {
                sh 'docker login --username=$DOCKER_HUB_LOGIN_USR --password=$DOCKER_HUB_LOGIN_PSW'
                sh './mailservice/gradlew -p ./mailservice dockerPush'
            }
        }
        stage('K8s deployment') {
            steps {
                sh 'kubectl apply -f app.yaml'
            }
        }
    }
}