version: '3'
services:
    db:
        image: mysql:5.7
        container_name: db
        networks:
            - mynet
        environment:
            MYSQL_DATABASE: subscriptiondb
            MYSQL_ROOT_PASSWORD: root
    mail:
        image: txtbits/mail:0.0.1-SNAPSHOT
        container_name: mail
        networks:
            - mynet
        ports:
            - 8887:8887
        environment:
            - SPRING_MAIL_HOST=mailhog
            - SERVER_PORT=8887
            - PRIVATE_URL=http://subscription:8886
    subscription:
        image: txtbits/subscription:0.0.1-SNAPSHOT
        container_name: subscription
        networks:
            - mynet
        ports:
            - 8886:8886
        environment:
            - SERVER_PORT=8886
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/subscriptiondb
            - MAIL_URL=http://mail:8887
        depends_on: 
            - db
    public:
        image: txtbits/public:0.0.1-SNAPSHOT
        container_name: public
        networks:
            - mynet
        ports:
            - 8885:8885
        environment:
            - SERVER_PORT=8885
            - PRIVATE_URL=http://subscription:8886
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        networks:
            - mynet
        ports:
            - 1025:1025
            - 8025:8025
networks:
    mynet:
        driver: bridge
