spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:hsqldb:file:subscriptiondb
    username: sa
    password:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true