eureka:
  client:
    service-url: 
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  profiles:
    active: docker
  datasource:
    url: jdbc:mysql://db:3306/subscriptiondb
    username: user
    password: pass
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: create

server:
  port: 8886
