spring:
  profiles:
    active: pro
  datasource:
    url: jdbc:mysql://localhost:3306/subscriptiondb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 8886
