server:
  port: 8886

spring:
  application:
    name: subscription
  main:
    allow-bean-definition-overriding: true

public:
  url: http://localhost:8885

private:
  url: http://localhost:8886
  user: admin
  pass: adminpass

mail:
  url: http://localhost:8887
  user: admin
  pass: adminpass
  attemps: 5